---
- hosts: all
  become: yes
  tasks:
  - name: installing apache2
    apt:
      name: apache2
      state: present
      update_cache: yes 
  - name: installing mysql-server
    apt:
      name: mysql-server
      state: present
  - name: installing php libapache2-mod-php php-mcrypt php-mysql
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php5
      - libapache2-mod-php5
      - php5-mcrypt
      - php5-mysql   
  - name: adding file
    copy:
      dest: "/var/www/html/info.php"
      content: |
        <?php
        phpinfo();
        ?>
